"""portfolio id none

Revision ID: 5b266c48cad5
Revises: abf9dcf59771
Create Date: 2024-03-08 12:26:25.683923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b266c48cad5'
down_revision: Union[str, None] = 'abf9dcf59771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'portfolio_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'portfolio_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
